# Generated by Django 4.0.1 on 2022-01-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropofflocation',
            name='city',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
