# Generated by Django 4.0.1 on 2022-01-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0002_dropofflocation_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropofflocation',
            name='location_address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dropofflocation',
            name='location_description',
            field=models.CharField(max_length=1000),
        ),
    ]
