# Generated by Django 4.0.1 on 2022-01-19 20:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0003_alter_dropofflocation_location_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropofflocation',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
        ),
        migrations.AlterField(
            model_name='dropofflocation',
            name='x',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='dropofflocation',
            name='y',
            field=models.FloatField(default=None),
        ),
    ]
