# Generated by Django 4.0.1 on 2022-01-19 22:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0004_alter_dropofflocation_point_alter_dropofflocation_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropofflocation',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=3857),
        ),
    ]
