# Generated by Django 4.0.1 on 2022-01-20 23:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0006_alter_dropofflocation_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropofflocation',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326),
        ),
    ]
