# Generated by Django 4.0.1 on 2022-01-20 23:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0007_alter_dropofflocation_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDropoffLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood_name', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=100)),
                ('location_description', models.CharField(max_length=1000)),
                ('location_address', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('x', models.FloatField(default=None)),
                ('y', models.FloatField(default=None)),
                ('point', django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326)),
                ('city', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dropofflocation',
            name='city',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
