# Generated by Django 4.0.1 on 2022-01-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0011_alter_adddropofflocation_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddropofflocation',
            name='x',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='adddropofflocation',
            name='y',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
