# Generated by Django 4.0.1 on 2022-01-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0012_alter_adddropofflocation_x_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adddropofflocation',
            old_name='x',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='adddropofflocation',
            old_name='y',
            new_name='longitude',
        ),
    ]
