# Generated by Django 4.0.1 on 2022-01-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0013_rename_x_adddropofflocation_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctdropofflocation',
            name='x',
        ),
        migrations.RemoveField(
            model_name='correctdropofflocation',
            name='y',
        ),
        migrations.RemoveField(
            model_name='dropofflocation',
            name='x',
        ),
        migrations.RemoveField(
            model_name='dropofflocation',
            name='y',
        ),
        migrations.RemoveField(
            model_name='votedropofflocation',
            name='x',
        ),
        migrations.RemoveField(
            model_name='votedropofflocation',
            name='y',
        ),
        migrations.AddField(
            model_name='correctdropofflocation',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='correctdropofflocation',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dropofflocation',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dropofflocation',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='votedropofflocation',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='votedropofflocation',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
