# Generated by Django 4.0.1 on 2022-01-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0014_remove_correctdropofflocation_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votedropofflocation',
            name='latitude',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='votedropofflocation',
            name='longitude',
            field=models.FloatField(default=None, null=True),
        ),
    ]
