# Generated by Django 4.0.1 on 2022-01-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0015_alter_votedropofflocation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votedropofflocation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
