# Generated by Django 4.0.1 on 2022-01-21 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0016_alter_votedropofflocation_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adddropofflocation',
            old_name='url',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='correctdropofflocation',
            old_name='url',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='dropofflocation',
            old_name='url',
            new_name='website',
        ),
    ]
