# Generated by Django 4.0.1 on 2022-01-21 21:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0017_rename_url_adddropofflocation_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctdropofflocation',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='correctdropofflocation',
            name='location_address',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='correctdropofflocation',
            name='location_description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='correctdropofflocation',
            name='location_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='correctdropofflocation',
            name='neighborhood_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='correctdropofflocation',
            name='phone',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='correctdropofflocation',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='correctdropofflocation',
            name='website',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
