# Generated by Django 4.0.1 on 2022-01-25 15:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0018_alter_correctdropofflocation_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropofflocation',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dropofflocation',
            name='location_address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dropofflocation',
            name='location_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dropofflocation',
            name='location_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dropofflocation',
            name='neighborhood_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dropofflocation',
            name='phone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dropofflocation',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='dropofflocation',
            name='website',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
