# Generated by Django 4.0.1 on 2022-01-26 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dropoff_locations', '0019_alter_dropofflocation_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropofflocation',
            name='responsible_group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group'),
        ),
    ]
