# Generated by Django 4.0.1 on 2022-01-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0020_dropofflocation_responsible_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropofflocation',
            name='responsible_group',
        ),
    ]
