# Generated by Django 4.0.1 on 2022-02-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0021_remove_dropofflocation_responsible_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropofflocation',
            name='city',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dropofflocation',
            name='latitude',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dropofflocation',
            name='location_address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dropofflocation',
            name='location_description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dropofflocation',
            name='longitude',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dropofflocation',
            name='neighborhood_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dropofflocation',
            name='phone',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dropofflocation',
            name='website',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
