# Generated by Django 4.0.1 on 2022-02-06 16:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0023_remove_dropofflocation_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropofflocation',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326),
        ),
    ]
