# Generated by Django 4.0.1 on 2022-02-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0025_rename_adddropofflocation_suggestdropofflocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestdropofflocation',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suggestdropofflocation',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
