# Generated by Django 4.0.1 on 2022-02-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0026_suggestdropofflocation_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestdropofflocation',
            name='status',
            field=models.CharField(choices=[('awaiting review', 'Awaiting Review'), ('addded to map', 'Added to Map'), ('denied', 'Denied')], default='Awaiting Review', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suggestdropofflocation',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suggestdropofflocation',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suggestdropofflocation',
            name='latitude',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='suggestdropofflocation',
            name='longitude',
            field=models.FloatField(default=None, null=True),
        ),
    ]
