# Generated by Django 4.0.1 on 2022-02-08 02:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0028_alter_suggestdropofflocation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestdropofflocation',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='suggestdropofflocation',
            name='status',
            field=models.CharField(choices=[('awaiting review', 'Awaiting Review'), ('addded to map', 'Added to Map'), ('denied', 'Denied')], max_length=50),
        ),
    ]
