# Generated by Django 4.0.1 on 2022-02-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0029_alter_suggestdropofflocation_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestdropofflocation',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
