# Generated by Django 4.0.1 on 2022-02-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0031_alter_suggestdropofflocation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctdropofflocation',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correctdropofflocation',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correctdropofflocation',
            name='status',
            field=models.CharField(default='Awaiting Review', max_length=100),
        ),
    ]
