# Generated by Django 4.0.1 on 2022-01-25 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0019_alter_dropofflocation_city_and_more'),
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='sites',
        ),
        migrations.AddField(
            model_name='manager',
            name='site1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropoff_locations.dropofflocation'),
        ),
    ]
