# Generated by Django 4.0.1 on 2022-01-25 15:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0019_alter_dropofflocation_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managers', '0002_remove_manager_sites_manager_site1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manager',
            new_name='ManagerProfile',
        ),
    ]
