# Generated by Django 4.0.1 on 2022-01-25 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0019_alter_dropofflocation_city_and_more'),
        ('managers', '0003_rename_manager_managerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='site2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_2', to='dropoff_locations.dropofflocation'),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='site3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_3', to='dropoff_locations.dropofflocation'),
        ),
        migrations.AlterField(
            model_name='managerprofile',
            name='site1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_1', to='dropoff_locations.dropofflocation'),
        ),
    ]
