# Generated by Django 4.0.1 on 2022-02-02 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0022_alter_dropofflocation_city_and_more'),
        ('managers', '0004_managerprofile_site2_managerprofile_site3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropoff_locations.dropofflocation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managers.managerprofile')),
            ],
            options={
                'unique_together': {('user', 'site')},
            },
        ),
    ]
