# Generated by Django 4.0.1 on 2022-02-02 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managers', '0005_managersite'),
    ]

    operations = [
        migrations.AddField(
            model_name='managersite',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active'), ('cancelled', 'cancelled')], default='inactive', max_length=50),
        ),
        migrations.AlterField(
            model_name='managersite',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
