# Generated by Django 4.0.1 on 2022-02-02 21:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff_locations', '0022_alter_dropofflocation_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managers', '0006_managersite_status_alter_managersite_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManagerSite',
            new_name='ManagerSitePermission',
        ),
    ]
