# Generated by Django 4.0.1 on 2022-02-03 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managers', '0007_rename_managersite_managersitepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managersitepermission',
            name='status',
            field=models.CharField(choices=[('requested', 'requested'), ('active', 'active'), ('denied', 'denied'), ('cancelled', 'cancelled')], default='requested', max_length=50),
        ),
        migrations.AlterField(
            model_name='managersitepermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
