# Generated by Django 4.0.1 on 2022-02-06 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0008_alter_managersitepermission_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerprofile',
            name='site1',
        ),
        migrations.RemoveField(
            model_name='managerprofile',
            name='site2',
        ),
        migrations.RemoveField(
            model_name='managerprofile',
            name='site3',
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='sites',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='managers.managersitepermission'),
        ),
    ]
