# Generated by Django 4.0.1 on 2022-02-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0009_remove_managerprofile_site1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagerProfile',
        ),
    ]
